# Example with random matrix

In [13]:
import numpy as np
from numpy.linalg import svd
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

In [14]:
vmin = 0
vmax = 1
image_bias = 1 # sometimes 1
def plot_svd(A):
    n = len(A)
    U, S, V = svd(A)

    imgs = []
    for i in range(n):
        imgs.append(S[i]*np.outer(U[:,i],V[i]))

    combined_imgs = []
    for i in range(n):
        img = sum(imgs[:i+1])
        combined_imgs.append(img)
        print(np.round(img,2))
        print("=====")
    
    #print(imgs)
    
    print(combined_imgs)
    
    return U,S,V

In [15]:
P = np.array([[3,1,4,1],[5,9,2,6],[5,3,5,8],[9,7,9,3]])
U,S,V = plot_svd(P)

[[2.51 2.37 2.22 1.97]
 [6.07 5.72 5.37 4.77]
 [5.63 5.31 4.99 4.43]
 [7.88 7.43 6.98 6.19]]
=====
[[3.15 1.41 3.79 0.56]
 [4.87 7.53 2.44 7.43]
 [5.28 5.85 4.12 5.22]
 [8.85 5.96 9.36 4.03]]
=====
[[3.1  0.96 3.93 0.99]
 [5.03 8.99 1.98 6.  ]
 [4.98 3.01 5.01 8.  ]
 [8.96 7.02 9.03 3.  ]]
=====
[[3. 1. 4. 1.]
 [5. 9. 2. 6.]
 [5. 3. 5. 8.]
 [9. 7. 9. 3.]]
=====
[array([[2.5129268 , 2.37029143, 2.22496161, 1.97491746],
       [6.0691682 , 5.72467824, 5.37368069, 4.7697793 ],
       [5.63425954, 5.31445527, 4.98860976, 4.42798315],
       [7.87808152, 7.43091645, 6.97530422, 6.19141025]]), array([[3.15001871, 1.40791218, 3.78880714, 0.55746973],
       [4.8743301 , 7.5295786 , 2.44075653, 7.42814078],
       [5.27953502, 5.85029558, 4.11788081, 5.2171997 ],
       [8.84904357, 5.96419913, 9.35868823, 4.03114429]]), array([[3.10337436, 0.96150448, 3.92917454, 0.99445918],
       [5.02692418, 8.98997372, 1.98155328, 5.99855688],
       [4.98239762, 3.00655494, 5.01206002, 8.00094348],
    